import Films from '../types/films';

const FISH_FILMS : Films = [
  {
    id: 1,
    name: 'Brassic',
    genre: 'Comedy',
    year: 2019,
    isFavorite: true,
    ratingScore: 8.6,
    ratingLevel: 'Good',
    ratingCount: 292568,
    director: 'Jon Wright',
    about: '',
    posterSrc: '',
    videoSrc: 'https://10.react.pages.academy/static/film/video/dog.mp4',
  },
  {
    id: 2,
    name: 'The Green Mile',
    genre: 'Drama',
    year: 1999,
    isFavorite: true,
    ratingScore: 9.1,
    ratingLevel: 'Good',
    ratingCount: 788312,
    director: 'Frank Darabont',
    about: '',
    posterSrc: '',
    videoSrc: 'https://10.react.pages.academy/static/film/video/traffic.mp4',
  },
  {
    id: 3,
    name: 'Lock, Stock and Two smoking Barrels',
    genre: 'Comedy',
    year: 1998,
    isFavorite: true,
    ratingScore: 8.6,
    ratingLevel: 'Good',
    ratingCount: 463689,
    director: 'Guy Ritchie',
    about: '',
    posterSrc: '',
    videoSrc: 'https://10.react.pages.academy/static/film/video/traffic.mp4',
  },
  {
    id: 4,
    name: 'Жмурки',
    genre: 'Comedy',
    year: 2005,
    isFavorite: true,
    ratingScore: 7.2,
    ratingLevel: 'Good',
    ratingCount: 248577,
    director: 'Алексей Балабанов',
    about: '',
    posterSrc: '',
    videoSrc: 'https://10.react.pages.academy/static/film/video/dog.mp4',
  },
  {
    id: 5,
    name: 'A Beautiful Mind',
    genre: 'Drama',
    year: 2001,
    isFavorite: true,
    ratingScore: 8.5,
    ratingLevel: 'Good',
    ratingCount: 452065,
    director: 'Ron Howard',
    about: '',
    posterSrc: '',
    videoSrc: 'https://10.react.pages.academy/static/film/video/traffic.mp4',
  },
  {
    id: 6,
    name: 'Avatar',
    genre: 'Fiction',
    year: 2009,
    isFavorite: false,
    ratingScore: 8.0,
    ratingLevel: 'Good',
    ratingCount: 870173,
    director: 'James Cameron',
    about: '',
    posterSrc: '',
    videoSrc: 'https://10.react.pages.academy/static/film/video/dog.mp4',
  },
  {
    id: 7,
    name: 'A Young Doctor\'s Notebook & Other Stories',
    genre: 'Comedy',
    year: 2012,
    isFavorite: true,
    ratingScore: 7.3,
    ratingLevel: 'Good',
    ratingCount: 49817,
    director: 'Alex Hardcastle',
    about: '',
    posterSrc: '',
    videoSrc: 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
  },
  {
    id: 8,
    name: 'Wayne',
    genre: 'Comedy',
    year: 2019,
    isFavorite: true,
    ratingScore: 8.2,
    ratingLevel: 'Good',
    ratingCount: 179110,
    director: 'Steve Pink',
    about: '',
    posterSrc: '',
    videoSrc: 'https://10.react.pages.academy/static/film/video/dog.mp4',
  }
];

export default FISH_FILMS;
